name: flutter_example_app
description: A new Flutter example application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:
  intl_translation:
  flutter_cupertino_localizations: ^1.0.1
  dio: ^3.0.3
  shared_preferences: ^0.5.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true